spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:core}
      host: ${MONGODB_HOST:192.168.1.18}
      port: ${MONGODB_PORT:27017}
  redis:
    host: ${REDIS_HOST:192.168.1.18}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: 0
    timeout: 5000
minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.1.18:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:core}